cosmetics

diff --git a/bin/pubdocs b/bin/pubdocs
--- a/bin/pubdocs
+++ b/bin/pubdocs
@@ -16,6 +16,6 @@ yarn docs || error "failed to build docs"
 echo
 echo "copying docs..."
 echo
-rsync -avz ./docs/* deploy@a01.kb.universablockchain.com:/home/deploy/www/shared/public/system/static/uparsecjs >/dev/null || error "failed to copy docs"
+rsync -avz --info=progress2 ./docs/* deploy@a01.kb.universablockchain.com:/home/deploy/www/shared/public/system/static/uparsecjs || error "failed to copy docs"
 
 echo "done creating unversa gem docs on kb"
